### ISSUE TITLE
Update Signal != 1/0 prints an additional rectangle emoji in front

### ISSUE THREAD

**Issue by dement6d** [LukeSmithxyz/dwmblocks#103]
the Update Signal part of config.h causes a rectangle to be rendered before the icon/output of a block
i should also mention that the block click functions dont work for me but im not too familiar with that patch and if i need a corresponding patch for dwm as well for that to work, i dont have it

Heres a screenshot, changing the update signal to 1 fixed the issue for me
![image](https://user-images.githubusercontent.com/93228501/180858242-a351a8bd-e023-4fef-9601-bd43cdb09085.png)

**Comment by dement6d** [comment]
ill close this since its most likely an issue with dwmblocks itself, it happens with regular commands and not only scripts, sometimes i have to set the update signal to 0 to remove the box symbol too

**Comment by dement6d** [comment]
well i just tried regular dwmblocks and it seems like the issue only happens on this fork

**Comment by nacho-dz** [comment]
This is because you're not using the patch for dwm, so dwm tries to render the non-printable character corresponding to the signal number.

If you don't care about clickability you're better off with vanilla dwmblocks. Also possible is setting every signal number to 0 as you've noticed, here's why:

The following code from `getcmd()` sets the first character of the block to the signal number if it is not 0:

    if (block->signal)
    	{
    		output[0] = block->signal;
    		output++;
    	}
