### ISSUE TITLE
modules doubling

### ISSUE THREAD

**Issue by rhysday** [LukeSmithxyz/dwmblocks#33]
Date/clock module is doubling up. Seems to be triggered by too many modules in the bar? I have 15
<a href="https://imgur.com/pjFhRoZ.png">
  <img src="https://imgur.com/pjFhRoZ.png" />
</a>

**Comment by LukeSmithxyz** [comment]
The problem is located in the module to the left of the date. I remember the battery module used to do this.

I forget the exact cause, but it's usually when dwmblocks has to implicitly remove newlines. If your module natively has multi-line output, just remove that.

If you can't figure out what's wrong, could you provide a link to the script module?

There should be a way to permanently fix this little glitch, but I've never really looked into it.

**Comment by rhysday** [comment]
ah I see. Now I know why you do all that fancy stuff in the weather script. I was just doing 
curl "wttr.in/Timbuktu?format=%c%C+🥶%t+🌧%h+🌀%w&m"
