### ISSUE TITLE
the statuscmd patch doesn't seem to be compatible with barpadding

### ISSUE THREAD

**Issue by kronikpillow** [LukeSmithxyz/dwmblocks#7]
statuscmd patch that you just applied to dwmblocks & dwm doesn't seem to be compatible with the barpadding patch, when you have bar padding enabled and you click the ? icon it spawns and closes the window, also when you click between the newsboat icon and # it spawns my pulsemixer for some reason :D

**Comment by LukeSmithxyz** [comment]
I haven't actually been using padding in a while so I didn't notice this. Looks like all the other modules but the rightmost and leftmost one are working fine though.

I might look into it, but I was actually thinking of removing the padding patch because again, I don't really use it.

**Comment by serhanekmekci** [comment]
I don't use your build Luke but I just solved this and I know that you deleted bar-padding from your build but I came across this issue and wanted to leave a note for people who searches about this.

You just need to add side padding variable(sp) in buttonpress function, after that statuscmd correctly calculating x.

Here is buttonpress function from statuscmd that I patched to work with bar-paddin.

`
void
buttonpress(XEvent *e)
{
	unsigned int i, x, click, occ = 0;
	Arg arg = {0};
	Client *c;
	Monitor *m;
	XButtonPressedEvent *ev = &e->xbutton;

	click = ClkRootWin;
	/* focus monitor if necessary */
	if ((m = wintomon(ev->window)) && m != selmon) {
		unfocus(selmon->sel, 1);
		selmon = m;
		focus(NULL);
	}
	if (ev->window == selmon->barwin) {
		i = x = 0;
		for (c = m->clients; c; c = c->next)
			occ |= c->tags == 255 ? 0 : c->tags;
		do {
			/* do not reserve space for vacant tags */
			if (!(occ & 1 << i || m->tagset[m->seltags] & 1 << i))
				continue;
			x += TEXTW(tags[i]);
		} while (ev->x >= x && ++i < LENGTH(tags));
		if (i < LENGTH(tags)) {
			click = ClkTagBar;
			arg.ui = 1 << i;
		} else if (ev->x < x + blw)
			click = ClkLtSymbol;
		else if (ev->x > (x = selmon->ww - (int)TEXTW(stext) + lrpad - 2 * sp)) {
 			click = ClkStatusText;

			char *text = rawstext;
			int i = -1;
			char ch;
			dwmblockssig = 0;
			while (text[++i]) {
				if ((unsigned char)text[i] < ' ') {
					ch = text[i];
					text[i] = '\0';
					x += TEXTW(text) - lrpad;
					text[i] = ch;
					text += i+1;
					i = -1;
					if (x >= ev->x) break;
					dwmblockssig = ch;
				}
			}
		}
	} else if ((c = wintoclient(ev->window))) {
		focus(c);
		restack(selmon);
		XAllowEvents(dpy, ReplayPointer, CurrentTime);
		click = ClkClientWin;
	}
	for (i = 0; i < LENGTH(buttons); i++)
		if (click == buttons[i].click && buttons[i].func && buttons[i].button == ev->button
		&& CLEANMASK(buttons[i].mask) == CLEANMASK(ev->state))
			buttons[i].func(click == ClkTagBar && buttons[i].arg.i == 0 ? &arg : &buttons[i].arg);
}
`

This is related line I changed, just added minus 2 side padding variable since there is two sides of bar.

`else if (ev->x > (x = selmon->ww - (int)TEXTW(stext) + lrpad - 2 * sp)) { '
